spring.application.name=ai-generated-tweet-to-kafka-service
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

# ---- ai-generated-tweet-to-kafka-service ----
ai-generated-tweet-to-kafka-service.streaming-data-keywords[0]=Java
ai-generated-tweet-to-kafka-service.streaming-data-keywords[1]=Microservices
ai-generated-tweet-to-kafka-service.streaming-data-keywords[2]=Spring
ai-generated-tweet-to-kafka-service.streaming-data-keywords[3]=Kafka
ai-generated-tweet-to-kafka-service.streaming-data-keywords[4]=Elasticsearch


##OPENAI config


