spring.application.name=ai-generated-tweet-to-kafka-service
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
#spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.config.username=admin
spring.cloud.config.password=secret1234

##OPENAI config --DELETE before push
spring.ai.openai.api-key=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
