spring.application.name=config-server

server.port=8888
logging.level.ROOT=INFO
logging.level.org.springframework.cloud.config=DEBUG

spring.cloud.config.server.git.uri=file:///C:/Users/SudiptaSengupta/Playground/udemy/kafka/demo/microservices-demo/config-server-repository
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.fail-fast=true